User.all.destroy_all

users = User.create([
    { email: 'admin@petstohome.cl', password: 'admin1234', password_confirmation: 'admin1234' }
])

City.all.destroy_all

cities = City.create([
    {name: 'Algarrobo'},
    {name: 'Alhué'},
    {name: 'Alto Biobío'},
    {name: 'Alto del Carmen'},
    {name: 'Alto Hospicio'},
    {name: 'Ancud'},
    {name: 'Andacollo'},
    {name: 'Angol'},
    {name: 'Antártica'},
    {name: 'Antofagasta'},
    {name: 'Antuco'},
    {name: 'Arauco'},
    {name: 'Arica'},
    {name: 'Aysén'},
    {name: 'Buin'},
    {name: 'Bulnes'},
    {name: 'Cabildo'},
    {name: 'Cabo de Hornos'},
    {name: 'Cabrero'},
    {name: 'Calama'},
    {name: 'Calbuco'},
    {name: 'Caldera'},
    {name: 'Calera de Tango'},
    {name: 'Calera'},
    {name: 'Calle Larga'},
    {name: 'Camarones'},
    {name: 'Camiña'},
    {name: 'Canela'},
    {name: 'Cañete'},
    {name: 'Carahue'},
    {name: 'Cartagena'},
    {name: 'Cartagena'},
    {name: 'Casablanca'},
    {name: 'Castro'},
    {name: 'Catemu'},
    {name: 'Cauquenes'},
    {name: 'Cerrillos'},
    {name: 'Cerro Navia'},
    {name: 'Chaitén'},
    {name: 'Chanco'},
    {name: 'Chañaral'},
    {name: 'Chépica'},
    {name: 'Chiguayante'},
    {name: 'Chile Chico'},
    {name: 'Chillán Viejo'},
    {name: 'Chillán'},
    {name: 'Chimbarongo'},
    {name: 'Cholchol'},
    {name: 'Chonchi'},
    {name: 'Cisnes'},
    {name: 'Cobquecura'},
    {name: 'Cochamó'},
    {name: 'Cochrane'},
    {name: 'Codegua'},
    {name: 'Coelemu'},
    {name: 'Coihueco'},
    {name: 'Coinco'},
    {name: 'Colbún'},
    {name: 'Colchane'},
    {name: 'Colina'},
    {name: 'Collipulli'},
    {name: 'Coltauco'},
    {name: 'Combarbalá'},
    {name: 'Concepción'},
    {name: 'Conchalí'},
    {name: 'Concón'},
    {name: 'Constitución'},
    {name: 'Contulmo'},
    {name: 'Copiapó'},
    {name: 'Coquimbo'},
    {name: 'Coronel'},
    {name: 'Corral'},
    {name: 'Coyhaique'},
    {name: 'Cunco'},
    {name: 'Curacautín'},
    {name: 'Curacaví'},
    {name: 'Curaco de Vélez'},
    {name: 'Curanilahue'},
    {name: 'Curarrehue'},
    {name: 'Curepto'},
    {name: 'Curicó'},
    {name: 'Dalcahue'},
    {name: 'Diego de Almagro'},
    {name: 'Doñihue'},
    {name: 'El Bosque'},
    {name: 'El Carmen'},
    {name: 'El Monte'},
    {name: 'El Quisco'},
    {name: 'El Tabo'},
    {name: 'Empedrado'},
    {name: 'Ercilla'},
    {name: 'Estación Central'},
    {name: 'Florida'},
    {name: 'Freire'},
    {name: 'Freirina'},
    {name: 'Fresia'},
    {name: 'Frutillar'},
    {name: 'Futaleufú'},
    {name: 'Futrono'},
    {name: 'Galvarino'},
    {name: 'General Lagos'},
    {name: 'Gorbea'},
    {name: 'Graneros'},
    {name: 'Guaitecas'},
    {name: 'Hijuelas'},
    {name: 'Hualaihué'},
    {name: 'Hualañé'},
    {name: 'Hualpén'},
    {name: 'Hualqui'},
    {name: 'Huara'},
    {name: 'Huasco'},
    {name: 'Huechuraba'},
    {name: 'Illapel'},
    {name: 'Independencia'},
    {name: 'Iquique'},
    {name: 'Isla de Maipo'},
    {name: 'Isla de Pascua'},
    {name: 'Juan Fernández'},
    {name: 'La Cisterna'},
    {name: 'La Cruz'},
    {name: 'La Estrella'},
    {name: 'La Florida'},
    {name: 'La Granja'},
    {name: 'La Higuera'},
    {name: 'La Ligua'},
    {name: 'La Pintana'},
    {name: 'La Reina'},
    {name: 'La Serena'},
    {name: 'La Unión'},
    {name: 'Lago Ranco'},
    {name: 'Lago Verde'},
    {name: 'Laguna Blanca'},
    {name: 'Laja'},
    {name: 'Lampa'},
    {name: 'Lanco'},
    {name: 'Las Cabras'},
    {name: 'Las Condes'},
    {name: 'Lautaro'},
    {name: 'Lebu'},
    {name: 'Licantén'},
    {name: 'Limache'},
    {name: 'Linares'},
    {name: 'Litueche'},
    {name: 'Llaillay'},
    {name: 'Llanquihue'},
    {name: 'Lo Barnechea'},
    {name: 'Lo Espejo'},
    {name: 'Lo Prado'},
    {name: 'Lolol'},
    {name: 'Loncoche'},
    {name: 'Longaví'},
    {name: 'Lonquimay'},
    {name: 'Los Álamos'},
    {name: 'Los Andes'},
    {name: 'Los Ángeles'},
    {name: 'Los Lagos'},
    {name: 'Los Muermos'},
    {name: 'Los Sauces'},
    {name: 'Los Vilos'},
    {name: 'Lota'},
    {name: 'Lumaco'},
    {name: 'Machalí'},
    {name: 'Macul'},
    {name: 'Máfil'},
    {name: 'Maipú'},
    {name: 'Malloa'},
    {name: 'Marchihue'},
    {name: 'María Elena'},
    {name: 'María Pinto'},
    {name: 'Mariquina'},
    {name: 'Maule'},
    {name: 'Maullín'},
    {name: 'Mejillones'},
    {name: 'Melipeuco'},
    {name: 'Melipilla'},
    {name: 'Molina'},
    {name: 'Monte Patria'},
    {name: 'Mostazal'},
    {name: 'Mulchén'},
    {name: 'Nacimiento'},
    {name: 'Nancagua'},
    {name: 'Natales'},
    {name: 'Navidad'},
    {name: 'Negrete'},
    {name: 'Ninhue'},
    {name: 'Nogales'},
    {name: 'Nueva Imperial'},
    {name: 'Ñiquén'},
    {name: 'Ñuñoa'},
    {name: 'O’Higgins'},
    {name: 'Olivar'},
    {name: 'Ollagüe'},
    {name: 'Olmué'},
    {name: 'Osorno'},
    {name: 'Ovalle'},
    {name: 'Padre Hurtado'},
    {name: 'Padre las Casas'},
    {name: 'Paiguano'},
    {name: 'Paillaco'},
    {name: 'Paine'},
    {name: 'Palena'},
    {name: 'Palmilla'},
    {name: 'Panguipulli'},
    {name: 'Panquehue'},
    {name: 'Papudo'},
    {name: 'Paredones'},
    {name: 'Parral'},
    {name: 'Pedro Aguirre Cerda'},
    {name: 'Pelarco'},
    {name: 'Pelluhue'},
    {name: 'Pemuco'},
    {name: 'Pencahue'},
    {name: 'Penco'},
    {name: 'Peñaflor'},   
    {name: 'Peñalolén'},
    {name: 'Peralillo'},
    {name: 'Perquenco'},
    {name: 'Petorca'},
    {name: 'Peumo'},
    {name: 'Pica'},
    {name: 'Pichidegua'},
    {name: 'Pichilemu'},
    {name: 'Pinto'},
    {name: 'Pirque'},
    {name: 'Pitrufquén'},
    {name: 'Placilla'},
    {name: 'Portezuelo'},
    {name: 'Porvenir'},
    {name: 'Pozo Almonte'},
    {name: 'Primavera'},
    {name: 'Providencia'},
    {name: 'Puchuncaví'},
    {name: 'Pucón'},
    {name: 'Pudahuel'},
    {name: 'Puente Alto'},
    {name: 'Puerto Montt'},
    {name: 'Puerto Octay'},
    {name: 'Puerto Varas'},
    {name: 'Pumanque'},
    {name: 'Punitaqui'},
    {name: 'Punta Arenas'},
    {name: 'Puqueldón'},
    {name: 'Purén'},
    {name: 'Purranque'},
    {name: 'Putaendo'},
    {name: 'Putre'},
    {name: 'Puyehue'},
    {name: 'Queilén'},
    {name: 'Quellón'},
    {name: 'Quemchi'},
    {name: 'Quilaco'},
    {name: 'Quilicura'},
    {name: 'Quilleco'},
    {name: 'Quillón'},
    {name: 'Quillota'},
    {name: 'Quilpué'},
    {name: 'Quinchao'},
    {name: 'Quinta de Tilcoco'},
    {name: 'Quinta Normal'},
    {name: 'Quintero'},
    {name: 'Quirihue'},
    {name: 'Rancagua'},
    {name: 'Ránquil'},
    {name: 'Rauco'},
    {name: 'Recoleta'},
    {name: 'Renaico'},
    {name: 'Renca'},
    {name: 'Rengo'},
    {name: 'Requínoa'},
    {name: 'Retiro'},
    {name: 'Rinconada'},
    {name: 'Río Bueno'},
    {name: 'Río Claro'},
    {name: 'Río Hurtado'},
    {name: 'Río Ibáñez'},
    {name: 'Río Negro'},
    {name: 'Río Verde'},
    {name: 'Romeral'},
    {name: 'Saavedra'},
    {name: 'Sagrada Familia'},
    {name: 'Salamanca'},
    {name: 'San Antonio'},
    {name: 'San Bernardo'},
    {name: 'San Carlos'},
    {name: 'San Clemente'},
    {name: 'San Esteban'},
    {name: 'San Fabián'},
    {name: 'San Felipe'},
    {name: 'San Fernando'},
    {name: 'San Gregorio'},
    {name: 'San Ignacio'},
    {name: 'San Javier'},
    {name: 'San Joaquín'},
    {name: 'San José de Maipo'},
    {name: 'San Juan de la Costa'},
    {name: 'San Miguel'},
    {name: 'San Nicolás'},
    {name: 'San Pablo'},
    {name: 'San Pedro de Atacama'},
    {name: 'San Pedro de la Paz'},
    {name: 'San Pedro'},
    {name: 'San Rafael'},
    {name: 'San Ramón'},
    {name: 'San Rosendo'},
    {name: 'San Vicente'},
    {name: 'Santa Bárbara'},
    {name: 'Santa Cruz'},
    {name: 'Santa Juana'},
    {name: 'Santa María'},
    {name: 'Santiago'},
    {name: 'Santo Domingo'},
    {name: 'Sierra Gorda'},
    {name: 'Talagante'},
    {name: 'Talca'},
    {name: 'Talcahuano'},
    {name: 'Taltal'},
    {name: 'Temuco'},
    {name: 'Teno'},
    {name: 'Teodoro Schmidt'},
    {name: 'Tierra Amarilla'},
    {name: 'Tiltil'},
    {name: 'Timaukel'},
    {name: 'Tirúa'},
    {name: 'Tocopilla'},
    {name: 'Toltén'},
    {name: 'Tomé'},
    {name: 'Torres del Paine'},
    {name: 'Tortel'},
    {name: 'Traiguén'},
    {name: 'Treguaco'},
    {name: 'Tucapel'},
    {name: 'Valdivia'},
    {name: 'Vallenar'},
    {name: 'Valparaíso'},
    {name: 'Vichuquén'},
    {name: 'Victoria'},
    {name: 'Vicuña'},
    {name: 'Vilcún'},
    {name: 'Villa Alegre'},
    {name: 'Villa Alemana'},
    {name: 'Villarrica'},
    {name: 'Viña del Mar'},
    {name: 'Vitacura'},
    {name: 'Yerbas Buenas'},
    {name: 'Yumbel'},
    {name: 'Yungay'},
    {name: 'Zapallar'}
])